workflows:
  android-build:
    name: Build Juice Game APK
    max_build_duration: 10
    instance_type: mac_mini_m1
    scripts:
      - name: Get LÖVE Engine and Patch
        script: |
          # 1. نسخ الملفات من مجلد workflows إلى بيئة العمل الرئيسية
          cp .github/workflows/love-11.5-android-embed.apk ./engine.apk
          cp .github/workflows/juice.love ./juice.love
          
          # 2. دمج ملف اللعبة داخل الـ APK
          zip -g engine.apk juice.love
      - name: Rename Artifact
        script: |
          mv engine.apk final_game.apk
    artifacts:
      - final_game.apk
